Johanna-L/speakeasy

- app/controllers/bookings_controller.rb
- app/controllers/speaker_offerings_controller.rb
- config/routes.rb
- test/controllers/bookings_controller_test.rb
- test/controllers/speaker_offerings_controller_test.rb
routes:  deleted resources :user
Added ressources SO & Bookings
added SO et booking controller
> added SO & Bookings controllers

- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
Added navbar
With links to sign up, sign in, sign out
> navbar with links to sign in sign out sign up

- app/views/shared/_navbar.html.erb
/!\ Edit : navbar with sign up log in log out
> navbar with sign up log in log out

- db/migrate/20191119134944_add_title_to_speaker_offerings.rb
- db/schema.rb
**Changed db schema :** new column "title" in Speaker_Offering model
> added column title to speaker-offerings

- app/controllers/speaker_offerings_controller.rb
- app/views/speaker_offerings/index.html.erb
- app/views/speaker_offerings/new.html.erb
- app/views/speaker_offerings/show.html.erb
Controller SpeakerOfferings
action index, new, create, show
Views = index, show, new
> offerings begin

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- db/schema.rb
first home page with caroussel and 4 images and a CTA
> first home page done

- app/controllers/bookings_controller.rb
- app/views/bookings/new.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
booking has now a form and can be saved in database !
few other modifications : 
- link in home "Découvrez nos offres" maintenant actif
- profile picture now optional
> added bookings controller & view

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
with min height (to stick it to bottom whatever the size of content is)
> added le wagon footer

- app/views/bookings/new.html.erb
- app/views/pages/home.html.erb
rajout extension de fichiers dans la home
> extensions de fichiers photo

- db/seeds.rb
Rajout de 4 prestations - pour EMMA, Patrick, Balkany, Nabilla
> Rajout de prestations dans les seeds

- app/views/pages/home.html.erb
> photos home cliquables

- app/assets/stylesheets/pages/_speaker_offerings_list.scss
- app/views/speaker_offerings/index.html.erb
- app/views/speaker_offerings/new.html.erb
> Clickable cards

- db/migrate/20191121102142_remove_budget_from_speaker_offerings.rb
- db/migrate/20191121102415_add_column_budget_to_speaker_offerings.rb
- db/migrate/20191121103144_rename_column_title_to_description.rb
- db/migrate/20191121103340_change_column_description_to_text.rb
- db/schema.rb
Modification de la table SpeakerOfferings 
- Colonne Budget : type Integer
- Suppression de la colonne Title 
- Ajout de la colonne Description (type Text)
> migrations de bdd speaker offerings description et budget

- app/models/speaker_offering.rb
- app/views/pages/dashboard.html.erb
- db/migrate/20191121102142_remove_budget_from_speaker_offerings.rb
- db/seeds.rb
Dans le modèle SpeakerOffering
- Validation sur le Topic
Le rails db:seed fonctionne à nouveau
> réparation du modèle speaker offering

- app/views/pages/dashboard.html.erb
- app/views/speaker_offerings/show.html.erb
Dashboard - fixed bug in the view
When adding a new booking, a new row is created
> dashboard - bugfix in bookings table

- app/controllers/application_controller.rb
user is now send to his dashboard after successfull sign in
> redirect to dashboard after signin in

- app/assets/stylesheets/pages/_speaker_offering_Show.scss
- app/views/speaker_offerings/show.html.erb
Mise en forme de la show des speaker offerings sous forme de card
> mise en forme de la show des speaker-offerings

- app/assets/stylesheets/components/_footer.scss
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
> navbar sticky & french - footer sticky & smaller

- app/views/shared/_navbar.html.erb
> navbar now sticky (vs fixed) speaker show ok

- db/seeds.rb
updated versions for emma and didier
> Updated seeds for emma et didier

- db/seeds.rb
Change "Femme" to "artist" & "ambassadrice" 
Add NY & DC
Check-in localization fonts
> watson to artist ambassadrice updates MAJ NY DC

- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_speaker_offering_Show.scss
- app/assets/stylesheets/pages/_speaker_offerings_list.scss
- app/views/pages/dashboard.html.erb
Modification des cartes dans le dashboard
> Dashboaaard

- app/assets/stylesheets/pages/_speaker_offerings_list.scss
- app/views/pages/dashboard.html.erb
- app/views/speaker_offerings/index.html.erb
- app/views/speaker_offerings/show.html.erb
mise en page index - margin top, + icônes, & titre
mise en page show - margin top
dashboard - icônes
> details - mise en page, bonhommes
